### ISSUE TITLE
attempt to use this nice repo to connect my evbox Elvi to HA

### ISSUE THREAD

**Issue by vadercent** [ajvdw/evbox#1]
Hello, I was looking a long time for a way to connect my Elvi to HA and was very happy when I found your code here.
As I'm only a system engineer with a healthy interest in home automation (so not an electrician or programmer) I purchased a modbus module [(https://enri.nl/pcb/?page=modbus)](https://enri.nl/pcb/?page=modbus) that according to my limited knowledge and understanding should be able to work with your code.

Unfortunately, after connecting the RS485 cable to the Elvi (cfr. manual) en loading the code via ESPHome to the Wemos it doesn't seem to read any data.
I did modify the pins in the code according to the modbus board based on the example code from the seller [https://github.com/aiolos](url)

Could you maybe advice if I'm missing anything or what I should do to debug or something?

thanks in advance!
groeten, Tim

**Comment by ajvdw** [comment]
I've also tested with max485 based module. I found that they don't work with 3.3V based MCU's (like WEMOS D1). There is a board based on MAX3485 that also supports 3.3V. Please check which chip is on your board. I use this board https://nl.aliexpress.com/item/1005003899400279.html

**Comment by vadercent** [comment]
ok, thanks for this info. I'm just a bit disappointed by mentioned delivery time on aliexpress ...
could this board on Amazon, also based on MAX3485, maybe provide same functionality? 
[https://www.amazon.nl/DollaTek-Ontwikkeling-Accessoires-Accessoire-Verwijderbare/dp/B08HQMDKGR](url)

**Comment by ajvdw** [comment]
That one should work too....

**Comment by vadercent** [comment]
as I'm not a programmer I'm trying to understand the working of the code ... 
If I'm not mistaking the sensor 'sensor.netpower' is imported from HA, could you tell me what this sensor represents? 
Is it the actual power consumption of the house? 
e.g. what the DSMR reads as 'sensor.electricity_meter_power_consumption'?

**Comment by ajvdw** [comment]
It is the net power from the grid  measured by the smart meter.

Op di 24 jan. 2023 21:39 schreef T. De Pourcq ***@***.***>:
